seed: 1
dataset_type: RGBD
dataset_name: seq003
data_dir: ./data/${dataset_type}/
work_dir: ./${dataset_name}_work_dir/${dataset_type}/grad01_eikonal01_off1_EDR1/
latent_dim: 1  # 1 because only scalar time is used
num_workers: 0 # 16

dataset:
    module_name: my_dataset
    class_name: TempSdfDataset
    dataset_name: ${dataset_name}
    dataset_type: ${dataset_type}
    data_dir: ${data_dir}

    sdf_dir: ${data_dir}

    with_raw_mesh: True
    raw_mesh_dir: ${data_dir}/selected_circle_registrated_ptclouds_new_ICP_normalized/

    with_registration: False
    registration_dir: ${data_dir}/selected_circle_registrated_ptclouds_new_ICP_normalized/

    template_path: ${data_dir}/selected_circle_registrated_ptclouds_new_ICP_normalized/000000.ply # template
    num_samples: 8192
    split_cfg:
        train: train_200.json # split
        test: train_200.json # split

model: 
    sdf:
        module_name: implicit_ad
        class_name: ImplicitGenerator
        auto_decoder: True
        decoder:
            latent_size: 1
            dims : [ 512, 512, 512, 512, 512, 512, 512, 512 ]
            norm_layers : [0, 1, 2, 3, 4, 5, 6, 7]
            latent_in : [4]
            weight_norm : True
            xyz_dim : 3
            use_encoder: False
            encoder:
                type: 'frequency'
                input_dim: 3
                freq: 10
            colornet:
                hidden_dim: 64
                hidden_layer: 3
        use_NGP: False
        use_colornet: False
loss:
    ###### sdf ######
    # SDF loss
    sdf_weight: 1.0
    sdf_loss_type: 'L1'
    # color loss
    color_weight: 1.0
    color_loss_type: 'L1'
    # sdf grad loss
    grad_loss_weight: 0.1
    eikonal_loss_weight: 0.1
    offsurface_loss_weight: 1
    # sdf surface ARAP loss
    use_sdf_asap_epoch: 50000
    use_EDR: True
    EDR_loss_weight: 1
    simplify_mesh: True
    implicit_reg_type: 'dense_inverse'
    sample_latent_space: True
    sample_latent_space_type: 'line' # normal, line
    sdf_asap_weight: 0.001
    weight_asap: 0.1
    mu_asap: 0.0001
    add_mu_diag_to_hessian: True
    sdf_grid_size: 50
    x_range: [-0.5, 0.5] # [-0.4, 0.4]
    y_range: [-0.8, 0.8] # [-0.8, 0.8]
    z_range: [-0.5, 0.5] # [-0.7, 0.7]
    topology_PD_loss: False
    topo:
        meshgrid_size: 18
        PD_loss_weight: 1
        PD_begin_epoch: 10000
        PD_loss_type: identical


optimization:
    sdf:
        batch_size: 4
        lr: 0.001
        gammas:    [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5] # [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]
        milestones: [1000, 2000, 3000, 4000, 5000, 6000, 7000] # [1000, 2000, 3000, 4000, 5000, 6000, 7000]
        num_epochs: 10001
        
        lat_vecs: # currently not used because we do not have leanable latents
            # lr: 0.005
            test_lr: 0.001 # 0.005
            test_lr_decay: 0.1
            test_decay_step: 400
            num_test_epochs: 801
    
log:
    log_batch_interval: 100
    save_epoch_interval: 500
    save_latest_epoch_interval: 100